#!/usr/bin/env python3

import re
import unicodedata

def convert(s):
    s = s.replace("°", "έ")
    s = s.replace("≈", "ώ")
    s = s.replace("¤", "ί")
    s = s.replace("a", "α")
    s = s.replace("ã", "ά")
    s = s.replace("é", "ἀ")
    s = s.replace("ê", "ἄ")
    s = s.replace("g", "γ")
    s = s.replace("i", "ι")
    s = s.replace("k", "κ")
    s = s.replace("m", "μ")
    s = s.replace("n", "ν")
    s = s.replace("o", "ο")
    s = s.replace("Ò", "ό")
    s = s.replace("p", "π")
    s = s.replace("r", "ρ")
    s = s.replace("t", "τ")
    s = s.replace("v", "ω")
    s = s.replace("w", "ς")
    s = s.replace("y", "θ")
    s = s.replace("z", "ζ")
    s = s.replace("d", "δ")
    s = s.replace("e", "ε")
    s = s.replace("l", "λ")
    s = s.replace("f", "φ")
    s = s.replace("Æ", "ή")
    s = s.replace("h", "η")
    s = s.replace("Ê", "ύ")
    s = s.replace("õ", "ᾄ")
    s = s.replace("‡", "ἴ")
    s = s.replace("s", "σ")
    s = s.replace("x", "χ")
    s = s.replace("u", "υ")
    s = s.replace("b", "β")
    s = s.replace("è", "ἁ")
    s = s.replace("ë", "ἅ")
    s = s.replace("›", "ῖ")
    s = s.replace("j", "ξ")
    s = s.replace("c", "ψ")
    s = s.replace("î", "ἆ")
    s = s.replace("Ô", "ὖ")
    s = s.replace("È", "ὐ")
    s = s.replace("Ë", "ῦ")
    s = s.replace("∞", "ῆ")
    s = s.replace("&", "ᾳ")
    s = s.replace("ı", "ὁ")
    s = s.replace("«", "ῶ")
    s = s.replace("§", "ἐ")
    s = s.replace("•", "ἑ")
    s = s.replace("¶", "ἔ")
    s = s.replace("‰", "ἶ")
    s = s.replace("Â", "ἷ")
    s = s.replace("ß", "ἕ")
    s = s.replace("Î", "ὔ")
    s = s.replace("Í", "ὑ")
    s = s.replace("“", "ῷ")
    s = s.replace("√", "ᾗ")
    s = s.replace("≥", "ἤ")
    s = s.replace("∑", "ἦ")
    s = s.replace("≤", "ἡ")
    s = s.replace("¥", "ἥ")
    s = s.replace("±", "ἠ")
    s = s.replace("·", "ἵ")
    s = s.replace("ç", "ᾶ")
    s = s.replace(" \u0303", "ὅ")
    s = s.replace("Ù", "ὀ")
    s = s.replace("ˆ", "ὄ")
    s = s.replace("", "ὗ")
    s = s.replace("Ï", "ὕ")
    s = s.replace(" \u0307", "ῃ")
    s = s.replace("=", "ῥ")
    s = s.replace("ñ", "ᾴ")
    s = s.replace("œ", "ὧ")
    s = s.replace("»", "ὠ")
    s = s.replace("À", "ὥ")
    s = s.replace("...", "ὡ")

    return unicodedata.normalize("NFC", s)

with open("raw/dik-90.tsv") as f:
    for line in f:
        num, lemma, gloss = line.strip().split("\t")
        new_lemma = convert(unicodedata.normalize("NFC", lemma))
        if not re.match("[\u0370-\u03FF\u1F00-\u1FFF\-]+$", new_lemma):
            print(new_lemma)
            for ch in new_lemma:
                print(ch, hex(ord(ch)))
            print(num)
            quit()
        print(num, new_lemma, gloss, sep="\t")
